function renderDraft(){
  const turn=expectedDraftSlot(),mine=ownsPlayerSlot(turn),filled=S.picks.length===10,rounds=[1,2,3,4,5],member=membershipForSlot(turn),canSkip=mine&&!member?.draft_skip_used;
  $("app").innerHTML=`<section class="card">${matchScoreboard()}<div class="sectionhead"><div><div class="eyebrow">BLIND DRAFT</div><h2>${filled?"Draft abgeschlossen":`Am Zug: ${esc(memberName(turn))}`}</h2></div><span class="chip">${S.picks.length}/10 Künstler</span></div>${S.error?`<div class="notice error">${esc(S.error)}</div>`:""}${mine&&!filled?`<div class="artistdraw">${S.currentArtist&&S.currentArtistSlot===turn?`${S.currentArtist.image?`<img src="${esc(S.currentArtist.image)}">`:""}<h2>${esc(S.currentArtist.name)}</h2><p class="muted">Wähle eine freie Runde für diesen Künstler.</p><div class="actions centered">${canSkip?`<button class="btn danger" id="skipArtist">Einmaligen Skip benutzen</button>`:`<span class="chip">Draft-Skip bereits benutzt</span>`}</div>`:`<h2>?</h2><p class="muted">Ziehe einen zufälligen Künstler aus deinem persönlichen Spotify-Pool.</p><button class="btn primary" id="drawArtist">Künstler ziehen</button>`}</div>`:`<div class="notice">${filled?"Die fünf Themen werden jetzt aufgedeckt.":"Warte auf den anderen Spieler."}</div>`}<div class="roundgrid">${rounds.map(n=>{const a=S.picks.find(p=>p.round_number===n&&p.player_slot===1),b=S.picks.find(p=>p.round_number===n&&p.player_slot===2),free=mine&&S.currentArtist&&S.currentArtistSlot===turn&&!S.picks.some(p=>p.round_number===n&&p.player_slot===turn);return`<div class="roundslot ${free?"selectable":""}" data-round="${n}"><div class="roundnum">Runde ${n}${n===5?" · ×2":""}</div><div class="pick">${a?esc(a.artist_name):"Spieler 1 · frei"}</div><div class="pick">${b?esc(b.artist_name):"Spieler 2 · frei"}</div></div>`}).join("")}</div>${roomExitControls()}</section>`;
  if($("drawArtist"))$("drawArtist").onclick=()=>drawArtist(turn);if($("skipArtist"))$("skipArtist").onclick=()=>useDraftSkip(turn);
  document.querySelectorAll(".roundslot.selectable").forEach(x=>x.onclick=()=>placeArtist(Number(x.dataset.round)));bindRoomExitControls();
  if(filled&&isHost()&&(S.rounds||[]).length===0&&S.room?.status!=="battle")initializeRounds();
}
async function submitTrack(slotNo,track){
  const r=currentRound();if(!r)return;const old=currentSubs()[slotNo-1];
  if(old){S.error="Dein Song ist bereits eingereicht und kann nicht mehr geändert werden.";render();return}
  const payload={round_id:r.id,room_id:S.room.id,player_user_id:S.user.id,player_slot:slotNo,spotify_track_id:track.id,spotify_uri:track.uri,song_name:track.name,artist_name:track.artist,album_name:track.album,album_image_url:track.image,start_ms:25000};
  const {error}=await sb.from("mb_submissions").insert(payload);if(error)S.error=error.message;else{S.searchResults[slotNo]=[];S.notice="Song eingereicht und gesperrt."}await reloadRoomNow();
}
function trackSide(slotNo,pick,sub,both){
  const mine=ownsPlayerSlot(slotNo),results=S.searchResults[slotNo]||[],artist=`<div class="artistline">${pick?.artist_image_url?`<img src="${esc(pick.artist_image_url)}">`:""}<div><div class="eyebrow">${esc(memberName(slotNo))}</div><h3>${esc(pick?.artist_name||"")}</h3></div></div>`;
  if(!mine&&!both)return`<div class="side">${artist}<div class="lockedpick"><div class="lockicon">●</div><strong>${sub?"Song eingereicht":"Wählt noch…"}</strong><span>Die Songwahl bleibt geheim, bis beide bestätigt haben.</span></div></div>`;
  if(mine&&!sub)return`<div class="side">${artist}<div style="margin-top:14px"><div class="playcontrols"><input id="songSearch${slotNo}" value="${esc(S.searchQuery[slotNo]||"")}" placeholder="Song suchen…" autocomplete="off"><button class="btn primary" data-search-slot="${slotNo}">Suchen</button></div><div class="results">${results.map(t=>`<div class="track" data-slot="${slotNo}" data-id="${esc(t.id)}">${t.image?`<img src="${esc(t.image)}">`:"<span></span>"}<div><strong>${esc(t.name)}</strong><small>${esc(t.album)}</small></div><span class="chip">Einreichen</span></div>`).join("")}</div></div><div class="notice" style="margin-top:10px">Nach dem Einreichen kann der Song nicht mehr gewechselt werden.</div></div>`;
  if(sub&&!both)return`<div class="side">${artist}<div class="selected"><strong>Song eingereicht</strong><div class="muted">Die Auswahl bleibt bis zur Einreichung beider Spieler verborgen.</div>${mine?`<div class="lockbadge">✓ Song gesperrt</div><label style="margin-top:12px">Startpunkt: <span id="startLabel${slotNo}">${Math.round((sub.start_ms||0)/1000)}s</span></label><input type="range" class="range" min="0" max="90" value="${Math.round((sub.start_ms||0)/1000)}" id="start${slotNo}">`:""}</div></div>`;
  if(sub)return`<div class="side">${artist}<div class="selected"><strong>${esc(sub.song_name)}</strong><div class="muted">${esc(sub.artist_name)} · ${esc(sub.album_name||"")}</div>${mine?`<div class="lockbadge">✓ Song gesperrt</div><label style="margin-top:12px">Startpunkt: <span id="startLabel${slotNo}">${Math.round((sub.start_ms||0)/1000)}s</span></label><input type="range" class="range" min="0" max="90" value="${Math.round((sub.start_ms||0)/1000)}" id="start${slotNo}"><div class="playcontrols"><button class="btn green" data-play="${slotNo}">▶ Abspielen</button><button class="btn" data-pause="${slotNo}">❚❚ Pause</button></div>`:""}</div></div>`;
  return`<div class="side">${artist}<p class="muted">Wartet auf Songauswahl…</p></div>`;
}
function renderBattle(){
  const r=currentRound(),picks=currentPicks(),subs=currentSubs();if(!r){$("app").innerHTML="<div class='card loading'>Runde wird vorbereitet…</div>";return}
  const both=Boolean(subs[0]&&subs[1]),hs=humanScores(),as=aiScores(),use=hs.length?hs:as,summary=use.length?scoreSummary(use):null;
  const roundLabel=r.round_number===6?"SUDDEN DEATH":`RUNDE ${r.round_number} VON 5${r.round_number===5?" · DOPPELTE PUNKTE":""}`;
  $("app").innerHTML=`<section class="card">${matchScoreboard()}<div class="battle-title"><div class="eyebrow">${roundLabel} · ${esc(r.category||"")}</div><h2>${esc(r.theme)}</h2></div>${S.error?`<div class="notice error">${esc(S.error)}</div>`:""}${S.notice?`<div class="notice">${esc(S.notice)}</div>`:""}<div class="match">${trackSide(1,picks[0],subs[0],both)}<div class="vs">VS</div>${trackSide(2,picks[1],subs[1],both)}</div>${both?renderJury(r,subs,hs,as,summary):`<div class="notice" style="margin-top:18px">Die Songs werden gleichzeitig aufgedeckt, sobald beide Spieler eingereicht haben.</div>`}${roomExitControls()}</section>`;
  document.querySelectorAll("[data-search-slot]").forEach(b=>b.onclick=()=>searchTracks(Number(b.dataset.searchSlot)));document.querySelectorAll(".track").forEach(x=>x.onclick=()=>{const n=Number(x.dataset.slot),t=(S.searchResults[n]||[]).find(t=>t.id===x.dataset.id);if(t)submitTrack(n,t)});
  [1,2].forEach(n=>{const el=$(`start${n}`);if(el&&ownsPlayerSlot(n)){el.oninput=()=>{$(`startLabel${n}`).textContent=el.value+"s"};el.onchange=()=>updateStart(n,Number(el.value)*1000)}});document.querySelectorAll("[data-play]").forEach(b=>b.onclick=()=>playSubmission(subs[Number(b.dataset.play)-1]));document.querySelectorAll("[data-pause]").forEach(b=>b.onclick=()=>pause(Number(b.dataset.pause)));
  if($("runAI"))$("runAI").onclick=runAIJury;if($("finalize"))$("finalize").onclick=finalizeRound;document.querySelectorAll("[data-human]").forEach(b=>b.onclick=()=>submitHumanScore(Number(b.dataset.human),b.dataset.close==="1"));if($("revealAllAI"))$("revealAllAI").onclick=()=>{S.aiReveal=5;render()};bindRoomExitControls();
}
