const SUPABASE_URL="https://swgraidbdxpjqnvxacpq.supabase.co";
const SUPABASE_KEY="sb_publishable_FsDT7WlBD5LJs2PPgkW0ww_BotUc0eX";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);

const SPOTIFY_CLIENT_ID="173f861652ae4b668769c76f0adab3a1";

const SPOTIFY={auth:"https://accounts.spotify.com/authorize",token:"https://accounts.spotify.com/api/token",api:"https://api.spotify.com/v1",scopes:"user-library-read user-top-read user-read-private user-read-email streaming user-read-playback-state user-modify-playback-state"};

const JUDGES={theme:{name:"Themenschnüffler",role:"Themen-Purist",image:"./assets/jury/themenschnueffler.webp"},vibe:{name:"Vibejunkie",role:"Atmosphäre-Juror",image:"./assets/jury/vibejunkie.webp"},lyrics:{name:"Kollegah der Lyricboss",role:"Lyrics-Juror",image:"./assets/jury/lyricboss.webp"},underdog:{name:"Snoop Underdogg",role:"David-vs-Goliath-Juror",image:"./assets/jury/snoop-underdogg.webp"},connoisseur:{name:"Dr. Körnli",role:"Musikkenner-Juror",image:"./assets/jury/dr-koernli.webp"}};
const THEMES={"Arena & Action":["Wrestling-Intro","Sunny Basketball Day"],"Kino & Charakter":["Superheld betritt die Szene","Bösewicht betritt die Szene","Filmtrailer für einen Gangsterfilm","Flucht vor der Polizei","Der letzte Song, bevor die Welt endet"],"Stadt & Nacht":["Nachtfahrt durch eine Grossstadt","Freitagabend","Samstag um 2 Uhr nachts","Du betrittst einen Raum und alle schauen"],"Sommer & Unterwegs":["Roadtrip mit Freunden","Cabrio im Sommer","Am Strand","Sonnenuntergang auf einem Dach"],"Wetter & Tageszeit":["Regentag in der Stadt","Erster warmer Tag im Frühling","Schneefall mitten in der Nacht","Sonntagmorgen","Montagmorgen"],"Party & Kultur":["OAFF Abriss","Kleine Underground-Party","2000er-Party","90er-Party"],"Emotion & Erinnerung":["Verliebt sein","Herzschmerz","Alle gegen dich","Motivationssong für schlechte Zeiten","Nostalgie"],"Attitude & Status":["Luxusleben","Selbstvertrauen auf Maximum","Diss-Track-Energie"]};
const S={user:null,room:null,members:[],picks:[],rounds:[],subs:[],scores:[],membership:null,currentArtist:null,currentArtistSlot:null,artistPools:{1:[],2:[]},spotifyProfiles:{1:null,2:null},spotify:{1:{access:"",refresh:"",expires:0,player:null,deviceId:""},2:{access:"",refresh:"",expires:0,player:null,deviceId:""}},searchResults:{1:[],2:[]},searchQuery:{1:"",2:""},notice:"",error:"",aiReveal:0};
const $=id=>document.getElementById(id);const esc=s=>String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
function roomStorage(){return JSON.parse(localStorage.getItem("mb_online_room")||"null")} function saveRoom(x){localStorage.setItem("mb_online_room",JSON.stringify(x))} function clearRoom(){localStorage.removeItem("mb_online_room")} function ownedMemberships(){return S.members.filter(m=>m.user_id===S.user?.id)} function membershipForSlot(slotNo){return S.members.find(m=>m.user_id===S.user?.id&&m.role==="player"&&m.player_slot===slotNo)||null} function ownsPlayerSlot(slotNo){return Boolean(membershipForSlot(slotNo))} function jurorMembership(){return S.members.find(m=>m.user_id===S.user?.id&&m.role==="juror")||null} function role(){return jurorMembership()?"juror":(ownedMemberships().some(m=>m.role==="player")?"player":null)} function slot(){const a=ownedMemberships().filter(m=>m.role==="player");return a.length===1?a[0].player_slot:null} function isHost(){return S.room?.host_user_id===S.user?.id} function memberName(slotNo){return S.members.find(m=>m.player_slot===slotNo)?.display_name||`Spieler ${slotNo}`} function juryScores(){return S.scores.filter(x=>x.round_id===currentRound()?.id)} function humanScores(){return juryScores().filter(x=>x.source==="human")} function aiScores(){return juryScores().filter(x=>x.source==="ai")} function currentRound(){return S.rounds.find(r=>r.round_number===Number(S.room?.current_round||1))} function currentPicks(){const n=Number(S.room?.current_round||1);return [S.picks.find(p=>p.round_number===n&&p.player_slot===1),S.picks.find(p=>p.round_number===n&&p.player_slot===2)]} function currentSubs(){const rid=currentRound()?.id;return [S.subs.find(x=>x.round_id===rid&&x.player_slot===1),S.subs.find(x=>x.round_id===rid&&x.player_slot===2)]}
async function ensureAnon(){const {data:{session}}=await sb.auth.getSession();if(session){S.user=session.user;return true}const {data,error}=await sb.auth.signInAnonymously({options:{data:{app:"music-battle"}}});if(error){S.error="Anonyme Anmeldung ist im Supabase-Projekt noch nicht aktiviert.";render();return false}S.user=data.user;return true}
async function init(){await ensureAnon();const saved=roomStorage();if(saved?.room_id){await loadRoom(saved.room_id);subscribeRoom()}await spotifyCallback();if(saved?.room_id)await loadRoom(saved.room_id);render()}
async function createRoom(){S.error="";const name=$("createName").value.trim();if(!name){S.error="Name ist erforderlich.";render();return}const {data,error}=await sb.rpc("mb_create_room",{p_display_name:name,p_jury_mode:"auto"});if(error){S.error=error.message;render();return}const row=data[0];saveRoom({room_id:row.room_id,code:row.room_code});await loadRoom(row.room_id);subscribeRoom();render()}
async function joinRoom(joinRole){S.error="";const code=$("joinCode").value.trim().toUpperCase(),name=$("joinName").value.trim();if(!code||!name){S.error="Raumcode und Name fehlen.";render();return}const {data,error}=await sb.rpc("mb_join_room",{p_room_code:code,p_display_name:name,p_role:joinRole});if(error){S.error=error.message;render();return}const row=data[0];saveRoom({room_id:row.room_id,code});await loadRoom(row.room_id);subscribeRoom();render()}
async function loadRoom(roomId){const [{data:room},{data:members},{data:picks},{data:rounds},{data:subs},{data:scores}]=await Promise.all([sb.from("mb_rooms").select("*").eq("id",roomId).single(),sb.from("mb_members").select("*").eq("room_id",roomId).order("joined_at"),sb.from("mb_draft_picks").select("*").eq("room_id",roomId).order("created_at"),sb.from("mb_rounds").select("*").eq("room_id",roomId).order("round_number"),sb.from("mb_submissions").select("*").eq("room_id",roomId).order("created_at"),sb.from("mb_jury_scores").select("*").eq("room_id",roomId).order("created_at")]);if(!room){clearRoom();return}S.room=room;S.members=members||[];S.picks=picks||[];S.rounds=rounds||[];S.subs=subs||[];S.scores=scores||[];S.membership=S.members.find(m=>m.user_id===S.user?.id)||null;restoreSpotify(1);restoreSpotify(2);restorePool(1);restorePool(2)}
let channel=null;function subscribeRoom(){if(!S.room)return;if(channel)sb.removeChannel(channel);channel=sb.channel(`mb-${S.room.id}`).on("postgres_changes",{event:"*",schema:"public",table:"mb_rooms",filter:`id=eq.${S.room.id}`},refresh).on("postgres_changes",{event:"*",schema:"public",table:"mb_members",filter:`room_id=eq.${S.room.id}`},refresh).on("postgres_changes",{event:"*",schema:"public",table:"mb_draft_picks",filter:`room_id=eq.${S.room.id}`},refresh).on("postgres_changes",{event:"*",schema:"public",table:"mb_rounds",filter:`room_id=eq.${S.room.id}`},refresh).on("postgres_changes",{event:"*",schema:"public",table:"mb_submissions",filter:`room_id=eq.${S.room.id}`},refresh).on("postgres_changes",{event:"*",schema:"public",table:"mb_jury_scores",filter:`room_id=eq.${S.room.id}`},refresh).subscribe()} let refreshTimer=null;function refresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(async()=>{await loadRoom(S.room.id);render()},120)} async function reloadRoomNow(){if(!S.room?.id)return;await loadRoom(S.room.id);render()}
