/* jury-ui */
// Rangfolge pro Runde (Entscheid 1.1): mit Juror im Raum zählt nur die menschliche Jury;
// ohne Juror schlägt ein eigener Entscheid des Hosts die Auto-Jury. Nie gemischt.
function isSelfDecision(s){return s?.source==="human"&&s?.details?.kind==="self_decision"}
function roundDecision(roundId,live=false){
  const sc=S.scores.filter(s=>s.round_id===roundId);
  const juror=sc.filter(s=>s.source==="human"&&!isSelfDecision(s));
  if(juror.length||(live&&S.members.some(m=>m.role==="juror")))return{kind:"juror",scores:juror};
  const self=sc.filter(isSelfDecision);
  if(self.length)return{kind:"self",scores:self.slice(-1)};
  const ai=sc.filter(s=>s.source==="ai");
  return ai.length?{kind:"ai",scores:ai}:{kind:"none",scores:[]};
}
function selfDecisionButtons(subs){return`<button class="btn" data-self-winner="1">A · ${esc(subs[0].song_name)}</button><button class="btn" data-self-winner="2">B · ${esc(subs[1].song_name)}</button>`}
function finalizeLabel(r){return r.round_number===5?"Runde 5 übernehmen · ×2":r.round_number===6?"Sudden Death übernehmen":"Runde übernehmen"}
function renderJury(r,subs,hs,as,summary){
  const self=hs.filter(isSelfDecision).slice(-1)[0],jurors=S.members.filter(m=>m.role==="juror");
  hs=hs.filter(s=>!isSelfDecision(s));
  if(role()==="juror"){const mine=hs.find(x=>x.juror_user_id===S.user.id);if(mine)return`<div class="juryarea"><div class="notice success">Deine Scorecard wurde abgegeben: ${mine.score_a}–${mine.score_b}</div></div>`;return`<div class="juryarea"><div class="sectionhead"><div><div class="eyebrow">DEINE SCORECARD</div><h2>Wer gewinnt?</h2></div></div><div class="human-score"><div class="choice"><b>Song A</b><div>${esc(subs[0].song_name)}</div><small>${esc(subs[0].artist_name)}</small><div class="actions"><button class="btn primary" data-human="1" data-close="0">10–8 klar</button><button class="btn" data-human="1" data-close="1">10–9 knapp</button></div></div><div class="choice"><b>Song B</b><div>${esc(subs[1].song_name)}</div><small>${esc(subs[1].artist_name)}</small><div class="actions"><button class="btn primary" data-human="2" data-close="0">10–8 klar</button><button class="btn" data-human="2" data-close="1">10–9 knapp</button></div></div></div></div>`}
  if(hs.length)return`<div class="juryarea"><div class="sectionhead"><div><div class="eyebrow">MENSCHLICHE JURY</div><h2>${hs.length} Scorecard${hs.length===1?"":"s"}</h2></div></div><div class="stack">${hs.map(s=>`<div class="member"><div><strong>${esc(s.juror_name)}</strong><small>${esc(s.reason||"")}</small></div><b>${s.score_a} – ${s.score_b}</b></div>`).join("")}</div>${isHost()?`<div class="actions"><button class="btn primary" id="finalize">Runde werten</button></div>`:""}</div>`;
  if(self&&!jurors.length){const w=Number(self.score_a)>Number(self.score_b)?1:2;return`<div class="juryarea"><div class="sectionhead"><div><div class="eyebrow">EIGENER ENTSCHEID</div><h2>${esc(memberName(w))} gewinnt die Runde</h2></div></div><div class="notice">„${esc(subs[w-1].song_name)}“ wurde vom Host als Rundensieger gewählt (${self.score_a}–${self.score_b}).</div>${isHost()?`<div class="actions centered"><button class="btn primary" id="finalize">${finalizeLabel(r)}</button></div>`:""}</div>`}
  if(jurors.length)return`<div class="juryarea"><div class="sectionhead"><div><div class="eyebrow">JURY</div><h2>Warte auf menschliche Scorecards</h2></div></div><div class="notice">${jurors.length} Juror${jurors.length===1?"":"en"} im Raum. Mit Juroren im Raum entscheidet ausschliesslich die menschliche Jury.</div></div>`;
  if(as.length){const shown=S.aiReveal>=5?as:[];return`<div class="juryarea"><div class="sectionhead"><div><div class="eyebrow">KI-JURY · FÜNF PERSÖNLICHKEITEN</div><h2>${S.aiReveal>=5?"Jury-Entscheid":"Urteil ist bereit"}</h2></div></div>${S.aiReveal<5?`<div class="juryready"><p>Alle fünf Juroren haben unabhängig bewertet.</p><button class="btn primary" id="revealAllAI">Alle Juroren aufdecken</button></div>`:`<div class="jurygrid">${shown.map(s=>{const j=JUDGES[s.juror_key]||{name:s.juror_name,role:"KI-Juror",image:""};return`<article class="judge">${j.image?`<img src="${j.image}">`:""}<div class="body"><div class="eyebrow">${esc(j.role)}</div><h4>${esc(j.name)}</h4><p class="muted">${esc(s.reason||"")}</p><div class="scorepair"><div class="score">A<br><b>${s.score_a}</b></div><div class="score">B<br><b>${s.score_b}</b></div></div></div></article>`}).join("")}</div><div class="finalscore"><div class="eyebrow">JURY SCORE</div><div class="big">${summary.a} – ${summary.b}</div><div>${summary.winner?`${esc(memberName(summary.winner))} gewinnt die Jury`:"Unentschieden"}</div></div>${isHost()?`<div class="actions centered"><button class="btn primary" id="finalize">${finalizeLabel(r)}</button></div>`:""}`}${isHost()?`<div class="choice" style="margin-top:14px"><div class="eyebrow">JURY ÜBERSTIMMEN</div><p class="muted">Ihr seht es anders? Wählt den Rundensieger selbst – das ersetzt das Jury-Urteil dieser Runde.</p><div class="actions">${selfDecisionButtons(subs)}</div></div>`:""}</div>`}
  return`<div class="juryarea"><div class="sectionhead"><div><div class="eyebrow">JURY</div><h2>Keine menschliche Jury</h2></div></div>${(isHost()?`<div class="grid2" style="margin-top:12px"><div class="choice"><div class="eyebrow">KI-JURY</div><h3>Fünf Juroren urteilen lassen</h3><p class="muted">Die KI-Jury bewertet beide Songs mit den vorhandenen Songdaten.</p><button class="btn primary" id="runAI">KI-Jury starten</button></div><div class="choice"><div class="eyebrow">SELBER ENTSCHEIDEN</div><h3>Ohne Jury weiterspielen</h3><p class="muted">Wenn ihr euch selbst einig seid, wählt den Rundensieger direkt. Der Entscheid zählt als knappe 10–9-Scorecard.</p><div class="actions">${selfDecisionButtons(subs)}</div></div></div>`:`<div class="notice">Der Host wählt zwischen KI-Jury und eigenem Entscheid.</div>`)}</div>`;
}
